Repository Exit1ofYeouido/BackEnd, pull requests merged in 2024-09, with the labels that each got.

#31 회원가입 시 Attendance 테이블에 회원 출석 정보 저장
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Kafka/Util/KafkaUtil.java
  Application/Reward/build/libs/reward-0.0.1-SNAPSHOT.jar
  Application/Reward/src/main/java/com/example/Reward/Attendance/Entity/Attendance.java
  Application/Reward/src/main/java/com/example/Reward/Attendance/Kafka/AttendanceDto.java
  Application/Reward/src/main/java/com/example/Reward/Attendance/Kafka/KafkaService.java
  Application/Reward/src/main/java/com/example/Reward/Config/KafkaConsumeConfig.java
Labels: feat

#36 Feat/search/#2
  Application/Home/src/main/java/com/example/Home/Member/MemberPoint.java
  Application/Search/build.gradle
  Application/Search/src/main/java/com/example/Search/Api/GeneratedToken.java
  Application/Search/src/main/java/com/example/Search/Api/KisService.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/Member.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/MemberStock.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/Stock.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/Token.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/TokenInfo.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/MemberRepository.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/MemberStockRepository.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/StockRepository.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/TokenInfoRepository.java
  Application/Search/src/main/java/com/example/Search/SearchController/SearchController.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/CurrentPriceDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/DailyStockPriceDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/MyStocksDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/OauthInfoDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/StockDetailDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/StockPriceListDTO.java
  Application/Search/src/main/java/com/example/Search/SearchDTO/StocksDTO.java
  Application/Search/src/main/java/com/example/Search/SearchService/SearchService.java
  Application/Search/src/main/resources/application.yml
Labels: feat

#38 Feat/sell stock/#27 -> develop
  Application/Auth/src/main/java/com/example/Auth/exception/GlobalException.java
  Application/Auth/src/main/java/com/example/Auth/kafka/consume/KafkaConsumeConfig.java
  Application/Mypage/build.gradle
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/Account.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/CompletedStockSale.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/MemberStock.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/SaleInfo.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSellRequest.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSellRequestA.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSellRequestB.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/Trade.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/AccountHistoryRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/CompletedStockSaleRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/MemberStockRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/SaleInfoRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/StockSaleRequestARepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/StockSaleRequestBRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Config/KafkaProducerConfig.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/AccountController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/MypageController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/in/StockSellRequestDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/MyStocksHistoryResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/ErrorResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/ExtractTrIdException.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/GlobalExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/MypageExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/config/WebSocketConfig.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/handler/StockPriceSocketHandler.java
  Application/Mypage/src/main/resources/application.yml
Labels: feat

#39 feat/search/#2 -> develop
  Application/Search/build.gradle
  Application/Search/src/main/java/com/example/Search/SearchController/StockController.java
Labels: enhancement

#47 Feat/sell stock/#41
  Application/Auth/src/main/java/com/example/Auth/entity/PhoneVerification.java
  Application/Home/gradle/wrapper/gradle-wrapper.jar
  Application/Mypage/build.gradle
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/CompletedStockSale.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/MemberStock.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/SaleInfo.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequest.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequestA.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequestB.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockTradeHistory.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/StockSaleRequestARepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/StockSaleRequestBRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/TradeRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Sms/MessageUtil.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/in/StockSellRequestDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/GlobalExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/NotFoundTokenException.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Dto/OauthInfoDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Entity/ApprovalKey.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Entity/TokenInfo.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Service/ApiService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Service/GeneratedToken.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/handler/StockPriceSocketHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/MypageApplication.java
  Application/Mypage/src/main/resources/application.yml
Labels: enhancement, feat

#51 fix : 오타로 인해 토큰 재발급 실패 수정
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Webclient/Service/GeneratedToken.java
Labels: feat

#65 Fix/service/#64
  Application/Auth/src/main/java/com/example/Auth/service/TokenService.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/CompletedStockSale.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
Labels: feat

#72 Feat/my account/#70
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequest.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequestA.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Entity/StockSaleRequestB.java
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/AccountRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/AccountController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/in/WithdrawalRequestDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/MyStockSaleRequestResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/PreWithdrawalResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/StockSaleConditionResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/WithdrawalResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/GlobalExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/InValidStockCodeException.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
Labels: enhancement, feat

#78 Feat/search/#75
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Search/src/main/java/com/example/Search/Common/Entity/TokenInfo.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/StockRepository.java
  Application/Search/src/main/java/com/example/Search/Search/Api/GeneratedToken.java
  Application/Search/src/main/java/com/example/Search/Search/Api/KisService.java
  Application/Search/src/main/java/com/example/Search/Search/SearchController/SearchController.java
  Application/Search/src/main/java/com/example/Search/Search/SearchDTO/SearchResponseDto.java
  Application/Search/src/main/java/com/example/Search/Search/SearchService/SearchService.java
  Application/Search/src/main/java/com/example/Search/SearchApplication.java
  Application/Search/src/main/resources/application.yml
Labels: enhancement

#74 fix : 보유주식 수익률 계산 오류 수정
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
Labels: bug

#82 fix: api호출 횟수줄이고 카멜케이스 변경!
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/AllAssetDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/GetAccountResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/GetAllMyPageResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
Labels: enhancement

#83 Feat/my account/#70
  Application/Home/src/main/java/com/example/Home/HomeService/HomeService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/AccountController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/StocksValueResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
Labels: bug, enhancement

#88 Feat/my account/#70
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/MyStocksResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
Labels: enhancement

#95 Refactor/my/#90
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/MemberStockRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/AccountController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/MyStocksPageResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
  Application/Search/src/main/java/com/example/Search/Search/Api/KisService.java
Labels: bug

#97 Refactor/my/#90
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/in/MemberSignupRequestDTO.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/GlobalExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SignupService.java
  Application/Search/src/main/java/com/example/Search/Exception/ErrorResult.java
  Application/Search/src/main/java/com/example/Search/Exception/GlobalExceptionHandler.java
  Application/Search/src/main/java/com/example/Search/Exception/NotAdminException.java
  Application/Search/src/main/java/com/example/Search/Log/Controller/LogController.java
  Application/Search/src/main/java/com/example/Search/Log/Service/LogService.java
Labels: enhancement

#109 Refactor/stock api/#105
  Application/Home/src/main/java/com/example/Home/Kis/GeneratedToken.java
  Application/Home/src/main/java/com/example/Home/Kis/KoreaInvestmentApiService.java
Labels: bug

#111 refactor : 관리자 권한 암호화
  Application/Search/src/main/java/com/example/Search/Log/Service/LogService.java
  Application/Search/src/main/resources/application.yml
Labels: enhancement

#116 fix : 오타수정
  Application/Search/src/main/java/com/example/Search/Log/Controller/LogController.java
Labels: bug

#117 Develop -> main
  Application/Home/src/main/java/com/example/Home/HomeService/HomeService.java
  Application/Home/src/main/java/com/example/Home/Kis/GeneratedToken.java
  Application/Home/src/main/java/com/example/Home/Kis/KoreaInvestmentApiService.java
  Application/Home/src/main/resources/application.yml
  Application/Mypage/src/main/java/com/example/Mypage/Common/Repository/MemberStockRepository.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Controller/AccountController.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/Other/EarningRate.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/in/MemberSignupRequestDTO.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/AllAssetDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/GetAccountResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/GetAllMyPageResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/GetPurchaseStocksResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Dto/out/MyStocksPageResponseDto.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Exception/GlobalExceptionHandler.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/AccountService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/MyService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SellService.java
  Application/Mypage/src/main/java/com/example/Mypage/Mypage/Service/SignupService.java
  Application/Reward/src/main/java/com/example/Reward/Advertisement/Dto/out/GiveStockResponseDto.java
  Application/Reward/src/main/java/com/example/Reward/Advertisement/Service/AdService.java
  Application/Reward/src/main/java/com/example/Reward/Attendance/Dto/out/Reward.java
  Application/Reward/src/main/java/com/example/Reward/Attendance/Service/AttendanceService.java
  Application/Reward/src/main/java/com/example/Reward/Common/Dto/DetailEnterPriseResponseDto.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Controller/ReceiptController.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Dto/out/RewardResponseDTO.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Dto/webClient/OCRResponseDTO.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Dto/webClient/StarbucksResponseDTO.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Exception/ReceiptErrorStatus.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Exception/ReceiptExceptionHandler.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Exception/ReceiptExceptions/ExistingPathException.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Repository/ReceiptLogRepository.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Service/OcrService.java
  Application/Reward/src/main/java/com/example/Reward/Receipt/Service/ReceiptService.java
  Application/Search/src/main/java/com/example/Search/Common/Repository/SearchLogRepository.java
  Application/Search/src/main/java/com/example/Search/Exception/ErrorResult.java
  Application/Search/src/main/java/com/example/Search/Exception/GlobalExceptionHandler.java
  Application/Search/src/main/java/com/example/Search/Exception/NotAdminException.java
  Application/Search/src/main/java/com/example/Search/Log/Controller/LogController.java
  Application/Search/src/main/java/com/example/Search/Log/Dto/out/MemberCountDto.java
  Application/Search/src/main/java/com/example/Search/Log/Dto/out/StockCountByYearDto.java
  Application/Search/src/main/java/com/example/Search/Log/Dto/out/StockCountDto.java
  Application/Search/src/main/java/com/example/Search/Log/Dto/out/StockCountResponseDto.java
  Application/Search/src/main/java/com/example/Search/Log/Service/LogService.java
  Application/Search/src/main/java/com/example/Search/Search/Api/KisService.java
  Application/Search/src/main/java/com/example/Search/Search/SearchService/SearchService.java
  Application/Search/src/main/resources/application.yml
  Application/reward/src/main/java/com/example/Reward/Receipt/Exception/ReceiptErrorStatus.java
  Application/reward/src/main/java/com/example/Reward/Receipt/Exception/ReceiptExceptionHandler.java
Labels: enhancement, feat
